sudo: false
cache: bundler
language: ruby
rvm:
- "2.3.3"
# - "2.4.1"
gemfile:
- gemfiles/chef-12.0.gemfile
- gemfiles/chef-12.1.gemfile
- gemfiles/chef-12.2.gemfile
- gemfiles/chef-12.3.gemfile
- gemfiles/chef-12.4.0.gemfile
- gemfiles/chef-12.4.gemfile
- gemfiles/chef-12.5.gemfile
- gemfiles/chef-12.6.gemfile
- gemfiles/chef-12.7.gemfile
- gemfiles/chef-12.gemfile
- gemfiles/master.gemfile
env:
  global:
  - USE_SYSTEM_GECODE=true
  - secure: bNxYOvi85lnPIPO1qR6NnhfqlREfMXSjmd+xCH01e/gg3x00D+3uyQIotQtglgHRItVIR36GqX70q2g/reudxBsCjfUhH2vDgbtmrWe1ow78rt1xZRlFMQs7JfBpfWKkox5i9mrdzZDekZACA0HUMI1pRM0MYQmkuol/oZw5H4A=
  - secure: ecX52GLF7IHCiaPEDzPtztiEmu2mNPfyyPrM7aaNsufat7DdsZqPP9LKpCTOoJC+Jgz9sdbQ6Hf61CeZAsrqZ8sKKdiXUoBUXdcBhvuPdpIbfwq97hjOoqQV7rLSD4EW58fipJU8Rl5P1ijFJizHIyxNB+VWBow3niIMGjIEUSE=
before_install:
- if [[ $BUNDLE_GEMFILE == *master.gemfile ]]; then gem update --system; fi
- gem --version
- gem install bundler
- bundle --version
- bundle config --local path ${BUNDLE_PATH:-vendor/bundle}
install: bundle update --jobs=3 --retry=3
script: bundle exec rake integration
