sudo: false
cache: bundler
language: ruby
matrix:
  include:
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.gemfile
    - rvm: 2.4.3
      gemfile: test/gemfiles/chef-13.gemfile
    - rvm: 2.1.4
      gemfile: test/gemfiles/chef-12.0.gemfile
    - rvm: 2.1.4
      gemfile: test/gemfiles/chef-12.1.gemfile
    - rvm: 2.1.4
      gemfile: test/gemfiles/chef-12.2.gemfile
    - rvm: 2.1.4
      gemfile: test/gemfiles/chef-12.3.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.4.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.4.0.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.5.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.6.gemfile
    - rvm: 2.1.6
      gemfile: test/gemfiles/chef-12.7.gemfile
    - rvm: 2.4.3
      gemfile: test/gemfiles/chef-13.7.6.gemfile
    - rvm: 2.5.0
      gemfile: test/gemfiles/master.gemfile
env:
  global:
  - USE_SYSTEM_GECODE=true
  - secure: bNxYOvi85lnPIPO1qR6NnhfqlREfMXSjmd+xCH01e/gg3x00D+3uyQIotQtglgHRItVIR36GqX70q2g/reudxBsCjfUhH2vDgbtmrWe1ow78rt1xZRlFMQs7JfBpfWKkox5i9mrdzZDekZACA0HUMI1pRM0MYQmkuol/oZw5H4A=
  - secure: ecX52GLF7IHCiaPEDzPtztiEmu2mNPfyyPrM7aaNsufat7DdsZqPP9LKpCTOoJC+Jgz9sdbQ6Hf61CeZAsrqZ8sKKdiXUoBUXdcBhvuPdpIbfwq97hjOoqQV7rLSD4EW58fipJU8Rl5P1ijFJizHIyxNB+VWBow3niIMGjIEUSE=
before_install:
- if [[ $BUNDLE_GEMFILE == *master.gemfile ]]; then gem update --system; fi
- gem --version
- gem install bundler
- bundle --version
- bundle config --local path ${BUNDLE_PATH:-vendor/bundle}
install: bundle update --jobs=3 --retry=3
script: bundle exec rake integration

